schedules:
  commit:
    # Run short suite on commit
    schedule: per_commit
    matrix:
      exclude:
        # Exclude all java 7 builds
        - java: oraclejdk7
        # Exclude java6 with dse-4.8 as testing with 5.0 should be adequate.
        - java: openjdk6
          cassandra: dse-4.8
    env_vars: |
      TEST_GROUP="short"
  nightly:
    # Run full suite nightly on change for all primary branches if they have changes.
    schedule: nightly
    branches:
      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, etc).
      include: ["/\\d+(\\.[\\dx]+)+/"]
    env_vars: |
      TEST_GROUP="long"
java:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
os:
  - ubuntu/trusty64
cassandra:
  - dse-4.8
  - dse-5.0
build:
  - script: |
      . /usr/local/bin/jdk_switcher.sh
      jdk_switcher use oraclejdk8
      export MAVEN_HOME=/home/jenkins/.mvn/apache-maven-3.2.5
      export PATH=$MAVEN_HOME/bin:$PATH
      mvn -B install -DskipTests
  - script: |
      . /usr/local/bin/jdk_switcher.sh
      jdk_switcher use $JAVA_VERSION
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -P$TEST_GROUP
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      cassandra.directory=$CCM_INSTALL_DIR
      dse=$CCM_IS_DSE
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      ccm.maxNumberOfNodes=3
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -Pisolated
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      cassandra.directory=$CCM_INSTALL_DIR
      dse=$CCM_IS_DSE
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      ccm.maxNumberOfNodes=3
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml" 
